title: IxVenture
description: Building something amazing with AI

# Repo-mode settings
url: ""
baseurl: ""

# Use empty baseurl by default, but allow GitHub Pages to override
# baseurl: "" 
# url: "https://ixventure.studio" 

theme: minima

# Site version
version: 0.1.15

collections:
  projects:
    output: true
    permalink: /projects/:path/

# Ensure static images are included
include:
  - assets
  - version.json
