title: IxVenture
description: Building something amazing with AI

# Repo-mode settings
url: ""
baseurl: ""

theme: minima

# Site version
version: 0.2.0

collections:
  projects:
    output: true
    permalink: /projects/:path/
  partnerships:
    output: true
    permalink: /partnerships/:path/

# Ensure static images are included
include:
  - assets
  - version.json
