title: IxVenture
description: Building something amazing with AI

# Repo-mode settings
url: "https://ixventure.studio"
baseurl: ""

theme: minima

# Site version
version: 0.1.15

collections:
  projects:
    output: true
    permalink: /projects/:path/

# Ensure static images are included
include:
  - assets
  - version.json
