title: IxVenture
description: Building something amazing with AI

# Repo-mode settings
url: "https://bestape.github.io"
baseurl: "/ixv-jekyll-minima-template"

# Use empty baseurl by default, but allow GitHub Pages to override
# baseurl: "" 
# url: "" 

theme: minima

# Site version
version: 0.1.14

collections:
  projects:
    output: true
    permalink: /projects/:path/

# Ensure static images are included
include:
  - assets
  - version.json
